// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_Button1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1798734781[6] = {&ui_img_1294260227, &ui_img_1294261252, &ui_img_1294262277, &ui_img_1294254854, &ui_img_1294255879, &ui_img_1294256904};
const lv_img_dsc_t *ui_imgset_1924271529[6] = {&ui_img_415547207, &ui_img_666181972, &ui_img_61900157, &ui_img_1497276386, &ui_img_1394264101, &ui_img_1818974016};
const lv_img_dsc_t *ui_imgset_dou[1] = {&ui_img_dou2_png};
const lv_img_dsc_t *ui_imgset_2046163424[1] = {&ui_img_813806129};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
