// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project3

#ifndef _SQUARELINE_PROJECT3_UI_H
#define _SQUARELINE_PROJECT3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_dou2_png);   // assets\dou2.png
LV_IMG_DECLARE( ui_img_813806129);   // assets\屏幕截图 2023-09-17 100240.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
