// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquarePrj

#include "../ui.h"

void ui_ScreenMain1_screen_init(void)
{
ui_ScreenMain1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMain1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenMain1, &ui_img_blue_brown_bg320_240_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_font(ui_ScreenMain1, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMain1 = lv_obj_create(ui_ScreenMain1);
lv_obj_set_width( ui_PanelMain1, 320);
lv_obj_set_height( ui_PanelMain1, 62);
lv_obj_set_align( ui_PanelMain1, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PanelMain1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMain1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMain1, lv_color_hex(0xFFDAB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMain1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMain1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMain1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_PanelMain1, lv_color_hex(0xB0D6EE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PanelMain1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_PanelMain1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_PanelMain1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_PanelMain1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_PanelMain1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnWeather1 = lv_imgbtn_create(ui_PanelMain1);
lv_imgbtn_set_src(ui_ImgBtnWeather1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_simple52_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnWeather1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_weather_simple60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnWeather1, 52);
lv_obj_set_width( ui_ImgBtnWeather1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnWeather1, -120 );
lv_obj_set_y( ui_ImgBtnWeather1, 0 );
lv_obj_set_align( ui_ImgBtnWeather1, LV_ALIGN_CENTER );
lv_obj_set_style_opa(ui_ImgBtnWeather1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnPlay1 = lv_imgbtn_create(ui_PanelMain1);
lv_imgbtn_set_src(ui_ImgBtnPlay1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video3o60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnPlay1, 60);
lv_obj_set_width( ui_ImgBtnPlay1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnPlay1, -40 );
lv_obj_set_y( ui_ImgBtnPlay1, 2 );
lv_obj_set_align( ui_ImgBtnPlay1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImgBtnPlay1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_ImgBtnSet1 = lv_imgbtn_create(ui_PanelMain1);
lv_imgbtn_set_src(ui_ImgBtnSet1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setting60_60_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnSet1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_setting60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnSet1, 60);
lv_obj_set_width( ui_ImgBtnSet1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnSet1, 120 );
lv_obj_set_y( ui_ImgBtnSet1, 0 );
lv_obj_set_align( ui_ImgBtnSet1, LV_ALIGN_CENTER );
lv_obj_set_style_blend_mode(ui_ImgBtnSet1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_ImgBtnSet1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnControl1 = lv_imgbtn_create(ui_PanelMain1);
lv_imgbtn_set_src(ui_ImgBtnControl1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_robot60_60_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnControl1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_robot60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnControl1, 60);
lv_obj_set_width( ui_ImgBtnControl1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnControl1, 40 );
lv_obj_set_y( ui_ImgBtnControl1, 0 );
lv_obj_set_align( ui_ImgBtnControl1, LV_ALIGN_CENTER );
lv_obj_set_style_blend_mode(ui_ImgBtnControl1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_ImgBtnControl1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_ScreenMain1);
lv_obj_set_width( ui_Panel1, 130);
lv_obj_set_height( ui_Panel1, 36);
lv_obj_set_x( ui_Panel1, 10 );
lv_obj_set_y( ui_Panel1, 0 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xB3D9EE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 160, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageBle1 = lv_img_create(ui_Panel1);
lv_img_set_src(ui_ImageBle1, &ui_img_bluetooth30_30_png);
lv_obj_set_width( ui_ImageBle1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageBle1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageBle1, -32 );
lv_obj_set_y( ui_ImageBle1, 0 );
lv_obj_set_align( ui_ImageBle1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageBle1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageBle1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageBle1, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageBle1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUsb1 = lv_img_create(ui_Panel1);
lv_img_set_src(ui_ImageUsb1, &ui_img_usb30_30_png);
lv_obj_set_width( ui_ImageUsb1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageUsb1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageUsb1, -1 );
lv_obj_set_y( ui_ImageUsb1, 0 );
lv_obj_set_align( ui_ImageUsb1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageUsb1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUsb1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageUsb1, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageUsb1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWifi1 = lv_img_create(ui_Panel1);
lv_img_set_src(ui_ImageWifi1, &ui_img_wifi30_30_png);
lv_obj_set_width( ui_ImageWifi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageWifi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageWifi1, 33 );
lv_obj_set_y( ui_ImageWifi1, 0 );
lv_obj_set_align( ui_ImageWifi1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWifi1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWifi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageWifi1, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageWifi1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePlay = lv_img_create(ui_ScreenMain1);
lv_img_set_src(ui_ImagePlay, &ui_img_hutao_15_png);
lv_obj_set_width( ui_ImagePlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePlay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePlay, 1 );
lv_obj_set_y( ui_ImagePlay, -14 );
lv_obj_set_align( ui_ImagePlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_ImgBtnWeather1, ui_event_ImgBtnWeather1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgBtnSet1, ui_event_ImgBtnSet1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgBtnControl1, ui_event_ImgBtnControl1, LV_EVENT_ALL, NULL);

}
