// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquarePrj

#include "../ui.h"

void ui_ScreenMain3_screen_init(void)
{
ui_ScreenMain3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMain3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenMain3, &ui_img_blue_brown_bg320_240_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_font(ui_ScreenMain3, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMain3 = lv_obj_create(ui_ScreenMain3);
lv_obj_set_width( ui_PanelMain3, 320);
lv_obj_set_height( ui_PanelMain3, 62);
lv_obj_set_align( ui_PanelMain3, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PanelMain3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMain3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMain3, lv_color_hex(0xFFDAB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMain3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMain3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMain3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_PanelMain3, lv_color_hex(0xB0D6EE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PanelMain3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_PanelMain3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_PanelMain3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_PanelMain3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_PanelMain3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnWeather3 = lv_imgbtn_create(ui_PanelMain3);
lv_imgbtn_set_src(ui_ImgBtnWeather3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_simple52_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnWeather3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_weather_simple60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnWeather3, 52);
lv_obj_set_width( ui_ImgBtnWeather3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnWeather3, -120 );
lv_obj_set_y( ui_ImgBtnWeather3, 0 );
lv_obj_set_align( ui_ImgBtnWeather3, LV_ALIGN_CENTER );
lv_obj_set_style_opa(ui_ImgBtnWeather3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnPlay3 = lv_imgbtn_create(ui_PanelMain3);
lv_imgbtn_set_src(ui_ImgBtnPlay3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_video3o60_60_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnPlay3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_video3o60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnPlay3, 60);
lv_obj_set_width( ui_ImgBtnPlay3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnPlay3, -40 );
lv_obj_set_y( ui_ImgBtnPlay3, 2 );
lv_obj_set_align( ui_ImgBtnPlay3, LV_ALIGN_CENTER );
lv_obj_set_style_opa(ui_ImgBtnPlay3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnSet3 = lv_imgbtn_create(ui_PanelMain3);
lv_imgbtn_set_src(ui_ImgBtnSet3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setting60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnSet3, 60);
lv_obj_set_width( ui_ImgBtnSet3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnSet3, 120 );
lv_obj_set_y( ui_ImgBtnSet3, 0 );
lv_obj_set_align( ui_ImgBtnSet3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImgBtnSet3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_blend_mode(ui_ImgBtnSet3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgBtnControl3 = lv_imgbtn_create(ui_PanelMain3);
lv_imgbtn_set_src(ui_ImgBtnControl3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_robot60_60_png, NULL);
lv_imgbtn_set_src(ui_ImgBtnControl3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_robot60_60_png, NULL);
lv_obj_set_height( ui_ImgBtnControl3, 60);
lv_obj_set_width( ui_ImgBtnControl3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgBtnControl3, 40 );
lv_obj_set_y( ui_ImgBtnControl3, 0 );
lv_obj_set_align( ui_ImgBtnControl3, LV_ALIGN_CENTER );
lv_obj_set_style_blend_mode(ui_ImgBtnControl3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_ImgBtnControl3, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_ScreenMain3);
lv_obj_set_width( ui_Panel4, 130);
lv_obj_set_height( ui_Panel4, 36);
lv_obj_set_x( ui_Panel4, 10 );
lv_obj_set_y( ui_Panel4, 0 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xB3D9EE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 160, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageBle3 = lv_img_create(ui_Panel4);
lv_img_set_src(ui_ImageBle3, &ui_img_bluetooth30_30_png);
lv_obj_set_width( ui_ImageBle3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageBle3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageBle3, -32 );
lv_obj_set_y( ui_ImageBle3, 0 );
lv_obj_set_align( ui_ImageBle3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageBle3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageBle3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageBle3, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageBle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageUsb3 = lv_img_create(ui_Panel4);
lv_img_set_src(ui_ImageUsb3, &ui_img_usb30_30_png);
lv_obj_set_width( ui_ImageUsb3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageUsb3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageUsb3, -1 );
lv_obj_set_y( ui_ImageUsb3, 0 );
lv_obj_set_align( ui_ImageUsb3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageUsb3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageUsb3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageUsb3, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageUsb3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWifi3 = lv_img_create(ui_Panel4);
lv_img_set_src(ui_ImageWifi3, &ui_img_wifi30_30_png);
lv_obj_set_width( ui_ImageWifi3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageWifi3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageWifi3, 33 );
lv_obj_set_y( ui_ImageWifi3, 0 );
lv_obj_set_align( ui_ImageWifi3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWifi3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWifi3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageWifi3, lv_color_hex(0xA6A6A6), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageWifi3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group = lv_obj_create(ui_ScreenMain3);
lv_obj_set_width( ui_Group, 254);
lv_obj_set_height( ui_Group, 130);
lv_obj_set_x( ui_Group, -1 );
lv_obj_set_y( ui_Group, -16 );
lv_obj_set_align( ui_Group, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Group, lv_color_hex(0xD0E7F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Group, lv_color_hex(0xFFDAB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Group, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Group, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Group, lv_color_hex(0xF9F5F5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Group, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_list1 = lv_obj_create(ui_Group);
lv_obj_set_width( ui_list1, lv_pct(100));
lv_obj_set_height( ui_list1, lv_pct(30));
lv_obj_set_align( ui_list1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_list1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_list1, lv_color_hex(0x095990), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_list1, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_list1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_list1, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_list1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_list1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_list1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_list1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_set_style_border_color(ui_list1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_list1);
lv_img_set_src(ui_Image9, &ui_img_usb30_30_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image9, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_list1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"USB Setting");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_list2 = lv_obj_create(ui_Group);
lv_obj_set_width( ui_list2, lv_pct(100));
lv_obj_set_height( ui_list2, lv_pct(30));
lv_obj_set_x( ui_list2, 0 );
lv_obj_set_y( ui_list2, 35 );
lv_obj_set_align( ui_list2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_list2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_list2, lv_color_hex(0x095990), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_list2, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_list2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_list2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_list2);
lv_img_set_src(ui_Image1, &ui_img_wifi30_30_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_list2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"WiFi Connect");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_list3 = lv_obj_create(ui_Group);
lv_obj_set_width( ui_list3, lv_pct(100));
lv_obj_set_height( ui_list3, lv_pct(30));
lv_obj_set_x( ui_list3, 0 );
lv_obj_set_y( ui_list3, 70 );
lv_obj_set_align( ui_list3, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_list3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_list3, lv_color_hex(0x095990), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_list3, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_list3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_list3, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list3, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_list3);
lv_img_set_src(ui_Image2, &ui_img_bluetooth30_30_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_list3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"BLE Connect");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_list4 = lv_obj_create(ui_Group);
lv_obj_set_width( ui_list4, lv_pct(100));
lv_obj_set_height( ui_list4, lv_pct(30));
lv_obj_set_x( ui_list4, 0 );
lv_obj_set_y( ui_list4, 105 );
lv_obj_set_align( ui_list4, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_list4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_list4, lv_color_hex(0x095990), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_list4, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_list4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_list4, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_list4);
lv_img_set_src(ui_Image3, &ui_img_api30_30_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image3, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_list4);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Serial Setting");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_list5 = lv_obj_create(ui_Group);
lv_obj_set_width( ui_list5, lv_pct(100));
lv_obj_set_height( ui_list5, lv_pct(30));
lv_obj_set_x( ui_list5, 0 );
lv_obj_set_y( ui_list5, 140 );
lv_obj_set_align( ui_list5, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_list5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_list5, lv_color_hex(0x095990), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_list5, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_list5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_list5, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_list5, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_list5);
lv_img_set_src(ui_Image4, &ui_img_more30_30_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_list5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"More");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgBtnWeather3, ui_event_ImgBtnWeather3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgBtnPlay3, ui_event_ImgBtnPlay3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgBtnControl3, ui_event_ImgBtnControl3, LV_EVENT_ALL, NULL);

}
