// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project3

#include "../ui.h"


// COMPONENT Switch Light

lv_obj_t *ui_Switch_Light_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Switch_Light;
cui_Switch_Light = lv_switch_create(comp_parent);
lv_obj_set_width( cui_Switch_Light, 90);
lv_obj_set_height( cui_Switch_Light, 40);
lv_obj_set_x( cui_Switch_Light, 0 );
lv_obj_set_y( cui_Switch_Light, 30 );
lv_obj_set_align( cui_Switch_Light, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(cui_Switch_Light, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Switch_Light, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(cui_Switch_Light, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_Switch_Light, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Switch_Light, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_Switch_Light, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Switch_Light, lv_color_hex(0x829DA2), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_Switch_Light, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_grad_color(cui_Switch_Light, lv_color_hex(0x006959), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_grad_dir(cui_Switch_Light, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_color(cui_Switch_Light, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(cui_Switch_Light, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_width(cui_Switch_Light, 5, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_border_side(cui_Switch_Light, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(cui_Switch_Light, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Switch_Light, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(cui_Switch_Light, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(cui_Switch_Light, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(cui_Switch_Light, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(cui_Switch_Light, LV_GRAD_DIR_VER, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_Switch_Light, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_shadow_opa(cui_Switch_Light, 255, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_shadow_width(cui_Switch_Light, 5, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_shadow_spread(cui_Switch_Light, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_x(cui_Switch_Light, -3, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_y(cui_Switch_Light, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(cui_Switch_Light, -5, LV_PART_KNOB| LV_STATE_CHECKED);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH_LIGHT_NUM);
children[UI_COMP_SWITCH_LIGHT_SWITCH_LIGHT] = cui_Switch_Light;
lv_obj_add_event_cb(cui_Switch_Light, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Switch_Light, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Switch_Light_create_hook(cui_Switch_Light);
return cui_Switch_Light; 
}

