// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: lv168

#include "../ui.h"

void ui_comp_Label1_create_hook( lv_obj_t * comp)
{
}

void ui_comp_Switch_Light_create_hook( lv_obj_t * comp)
{
}
