// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Label1

lv_obj_t *ui_Label1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Label1;
cui_Label1 = lv_label_create(comp_parent);
lv_obj_set_width( cui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label1, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(cui_Label1, &ui_font_Font3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL1_NUM);
children[UI_COMP_LABEL1_LABEL1] = cui_Label1;
lv_obj_add_event_cb(cui_Label1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Label1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Label1_create_hook(cui_Label1);
return cui_Label1; 
}

